name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env: {}

jobs:
  install-gems:
    name: Run with `install-gems`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: spinel-coop/setup-rv@7742b8d7664b17aa00c263164754cd32d4599955
        with:
          enable-cache: true
          install-gems: true

      - run: rv run ruby --version
      - run: rv run --verbose htmlproofer --version

  clean-install:
    name: Run with with separate `clean-install`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: spinel-coop/setup-rv@7742b8d7664b17aa00c263164754cd32d4599955
        with:
          enable-cache: true

      - run: rv clean-install
      - run: rv run ruby --version
      - run: rv run --verbose htmlproofer --version
